# The name of this session. This variable is only used for the uniquely
# identifying the log files when multiple datasets are analyzed at once,
# as in the case where individual runs / plates are saved as sub-directories
# within the `project_directory` root. In such a layout, each subsequent
# plate is appended with a numerical non-zero index which will specifically
# identify the session internally.
session_name: default


# If no random seed is defined for reproducibility, one will be set
# and reported to the user in the log file.
random_seed: Null


# The number of processes to use when running the analysis. By default, the
# number of processes used will be 1 to avoid mistakenly allocating system
# resources. If more processes are requested than available, the system will
# automatically set the number of processes to what's available to avoid
# performance degradation.
#
# If this is set to `Null`, the maximum number of available CPUs will
# be determined and used. For e.g. a quad-core CPU (no-hyper-threading)
# will result in 4 processes being simultaneously generated for use. If the
# cpu is dual-core but supports hyper-threading (i.e. virtual CPUs), then
# the number of processes generated will also be 4.
num_processes: 1


# This effectively sets the priority of the child process to the lowest.
# Useful if the number of processes approaches or exceeds the number of
# processes available to the system as using all the processes by default
# at their default nice level can overwhelm the system and degrade
# performance overall. In some cases this can slow down the overall
# analysis.
#
# Nice levels range from -20 (highest / realtime) to 19 (lowest). The
# default "nice-level" of processes are usually 0. Low nice-levels are good
# when there are processes competing for resources, which can lead to
# unresponsiveness.
nice_level: 19


# The location of the DAmFRET project that contains the gated FCS data.
# Will be checked at runtime. Requires a non-null argument.
#
# If individual datasets are stored as sub-directories under the path provided,
# the program will search and identify directories that contain files
# with the same format as `filename_format` (Barring default directories
# such as `work---<YYYY-mm-DD_HH-MM-SS>`, `logs---<YYYY-mm-DD_HH-MM-SS>`,
# and `raw_data`.
#
# This path can also be relative. For e.g. `'.'`.
project_directory: .


# A CSV file containing the well files which will be examined. If a relative
# path is provided, the path will be relative to the `project_directory`.
# For e.g. if our `project_directory` is `/tmp/20cy148.damfret` and the
# `wells_filename` is "wells.csv", this means that the actual path of
# filename on the filesystem is actually: `/tmp/20cy148.damfret/wells.csv`.
#
# If an absolute path is provided (external or internal to the
# `project_directory`) that path will be used.
#
# The purpose of this design is such that the user can directly refer to a
# CSV list which can be consulted on which well files should be analyzed.
# The purpose of this is such that if some wells are skipped due to the
# the concentration range exceeding the values provided in `low_conc`
# and `high_conc`, a subsequent analysis can be performed by referring to
# a different CSV file containing the previously "skipped" wells.
#
# If this parameter is not `Null`, the same list will be used when analyzing
# all the data. The program will use this reference list for all the sub
# directories in the `project_directory`. If each sub-directory contains
# a different number of wells, the resulting summary could be misleading.
#
# If this parameter is set to `Null`, the program examines each
# individual subdirectory that contains data (i.e. those with files
# containing files with names of the format `filename_format`) and builds
# its own table of the wells files that will be analyzed. This file,
# `wells.csv` will be saved in that directory root, and its value
# updated in the YAML sub-directory settings.
#
# The optimal solution is to keep this option set to `Null`.
wells_filename: Null


# The format of the gated FCS filenames in the `project_directory`.
# This name can be anything, but must contain `{well_name}` in its filename.
# For e.g. `'{well_name}.csv'`. Cannot be null.
filename_format: '{well_name}.fcs.csv'


# The location where the parameters and session log will be saved.
#
# If `Null`, a default directory called `work---<YYYY-mm-DD_HH-MM-SS>` will
# be created. `Null` is the default and preferred option as it isolates
# each run.
work_directory: Null


# The location where the intermediate log files will be created.
#
# If `Null`, a default directory called `logs---<YYYY-mm-DD_HH-MM-SS>` will
# be created. `Null` is the default and preferred option as it isolates
# each run.
logs_directory: Null


# Skip the analysis of files (usually gated well files) containing less
# than this number of measurements. These files will be marked as N/A
# in the final collated parameter file.
#
# This number is determined by analyzing the Shannon entropy of the
# dataset. See the SI of the DAmFRET manuscript for more.
minimum_required_measurements: 20000


# These are the limits of the data for the cutoff. This data is excluded
# as data the extrema are noisy.
#
# Data lower than this value will be excluded.
low_conc_cutoff: 1.5


# Data higher than this value will be excluded. Note: this should match
# the limit of `high_conc`.
high_conc_cutoff: 5.0


# Limits for the conc and FRET data. Data outside of these bounds are
# excluded. It should also be noted that before data is analyzed, it
# is first checked to determine if it is within these limits. The most
# important parameters for that check are those of concentration. If the
# data exceeds the upper limit, that dataset is excluded from the current
# analysis and marked as "N/A" in the output parameter file.
#
# Skipped well files are exported in a truncated CSV file of the original
# input. The purpose of this design is so that that file can then be
# consulted / referenced in a subsequent run in case there are files
# which are skipped.
low_conc: 0.0
high_conc: 5.0
low_fret: -1.0
high_fret: 1.0


# Set this value such This effectively creates ~25 bins within the
# current concentration range (i.e. `high_conc - low_conc`).
conc_bin_width: 0.2


# Set this value such that it effectively creates ~100 bins within the
# current FRET range (i.e. `high_fret - low_fret`). Higher resolution
# is required here since this bin width will be used to create a 1D
# histogram which profiles the FRET data within a concentration "slice".
# Using a larger bin width (less bins) would make the characterization
# of assembly within that profile more difficult.
fret_bin_width: 0.02


# This number is determined by an analysis of the Shannon Entropy of
# the dataset. It sets the number of bins in the x and y dimensions
# to be the same.
number_of_bins: 300


# Which plots to generate.
#
# 1) 2D histograms plots are the profiles of the raw data.
#
# 2) Gaussian fits plots contain the intermediate plots of the fits to
#    the 1D histograms of the FRET within a concentration "slice". As
#    this impacts the R^2 and logistic fits plots, it is useful for
#    debugging a run.
#
# 3) Logisitic fits plots are plots of logistic functions to the
#    R^2 values derived from the Gaussian fits. This is used to
#    determine whether a system has undergone a transition. Useful
#    for debugging.
#
# 4) R^2 fits plots are the plots of the fits to the R^2 values
#    extracted from the fit of Gaussian plots, which is used to
#    characterize assembly. Useful for diagnostic purposes.
#
# 5) For data that is not within the effective limits and are
#    skipped for subsequent analysis, it could be useful to examine
#    the profiles thereof and use that to determine what the effective
#    range should be. Note that the limits are auto-calculated
#    and not referenced from those provided in `xlim_2d_histogram`
#    and `ylim_2d_histogram`.
plot_2d_histograms: True
plot_gaussian_fits: True
plot_logistic_fits: True
plot_rsquared_fits: True
plot_skipped_2d_histograms: True


# Whether or not to move the plots from the `work` directory
# into the `project_directory`.
move_to_project_directory: True


# Limits to use when plotting the 2d-histograms / profiles that were
# not skipped.
xlim_2d_histogram: [1.5, 4.5]
ylim_2d_histogram: [-0.25, 0.75]


# The kind of plot type to output (default: PNG).
plot_type: png
